# Generated by Django 5.1.15 on 2025-12-08 16:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beverage_management', '0002_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('soft_drinks', 'Soft Drinks'), ('energy_drinks', 'Energy Drinks'), ('juices', 'Juices'), ('water', 'Water'), ('alcoholic', 'Alcoholic Beverages'), ('other', 'Other')], max_length=50)),
                ('brand', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('reorder_point', models.IntegerField(default=20)),
                ('unit', models.CharField(default='bottles', max_length=20)),
                ('location', models.CharField(help_text='Aisle-Shelf-Bin', max_length=50)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('supplier_name', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=50, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft (Encoding Details)'), ('pending_approval', 'Pending VP Signature'), ('approved', 'Approved (Signed)'), ('sent', 'Sent to Supplier'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('selection_justification', models.TextField(blank=True, help_text="Notes on physical canvass (e.g., 'Chosen based on physical canvass of 3 suppliers due to lowest price')")),
                ('is_signed_by_vp', models.BooleanField(default=False)),
                ('date_signed_vp', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'role': 'purchasing_officer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beverage_management.inventoryitem')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='beverage_management.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='ReceivingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rm_number', models.CharField(help_text='Receiving Memo #', max_length=50, unique=True)),
                ('delivery_receipt_no', models.CharField(help_text='Supplier DR #', max_length=100)),
                ('date_received', models.DateTimeField(auto_now_add=True)),
                ('quality_check_passed', models.BooleanField(default=False)),
                ('inspection_notes', models.TextField(blank=True, help_text='Notes on damages or expiry')),
                ('status', models.CharField(choices=[('pending', 'Inspection Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected (Damaged/Expired)')], default='pending', max_length=20)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beverage_management.purchaseorder')),
                ('received_by', models.ForeignKey(limit_choices_to={'role': 'warehouse_manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequisitionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rf_number', models.CharField(help_text='Auto-generated RF ID', max_length=50, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending_dept_head', 'Pending Dept Head Approval'), ('pending_vp', 'Pending VP Approval'), ('approved', 'Approved (Signed)'), ('rejected', 'Rejected'), ('in_process', 'In Process (Warehouse/Purchasing)'), ('closed', 'Closed')], default='pending_dept_head', max_length=30)),
                ('is_signed_by_dept_head', models.BooleanField(default=False)),
                ('date_signed_dept_head', models.DateField(blank=True, null=True)),
                ('is_signed_by_vp', models.BooleanField(default=False)),
                ('date_signed_vp', models.DateField(blank=True, null=True)),
                ('route_destination', models.CharField(blank=True, choices=[('warehouse', 'Warehouse (Pick List)'), ('purchasing', 'Purchasing (PO)')], max_length=20, null=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='requisition',
            field=models.ForeignKey(blank=True, help_text='Linked RF if applicable', null=True, on_delete=django.db.models.deletion.CASCADE, to='beverage_management.requisitionform'),
        ),
        migrations.CreateModel(
            name='InternalDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_delivered', models.DateTimeField(blank=True, null=True)),
                ('acknowledgement_receipt_signed', models.BooleanField(default=False)),
                ('received_by_staff_name', models.CharField(help_text='Name of staff who signed AR', max_length=100)),
                ('date_signed_ar', models.DateField(blank=True, null=True)),
                ('processed_by', models.ForeignKey(limit_choices_to={'role': 'warehouse_manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('requisition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='beverage_management.requisitionform')),
            ],
        ),
        migrations.CreateModel(
            name='RequisitionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_requested', models.IntegerField()),
                ('stock_available_at_check', models.BooleanField(default=False, help_text='Result of system inventory check')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beverage_management.inventoryitem')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='beverage_management.requisitionform')),
            ],
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('receive', 'Receiving (Add)'), ('adjust', 'Manual Adjustment'), ('damage', 'Damage/Wastage'), ('issue', 'Internal Issue (Deduct)'), ('set', 'Set Exact Quantity')], max_length=20)),
                ('quantity_change', models.IntegerField()),
                ('reason', models.CharField(max_length=200)),
                ('reference', models.CharField(blank=True, help_text='PO#, RM#, or RF#', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='beverage_management.inventoryitem')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='beverage_management.supplier'),
        ),
    ]
