# Generated by Django 5.1.15 on 2025-12-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beverage_management', '0003_inventoryitem_supplier_auditlog_purchaseorder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(choices=[('soft_drinks', 'Soft Drinks'), ('energy_drinks', 'Energy Drinks'), ('juices', 'Juices'), ('water', 'Water'), ('alcoholic', 'Alcoholic Beverages'), ('coffee_tea', 'Coffee/Tea'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='unit',
            field=models.CharField(choices=[('bottles', 'Bottles'), ('cans', 'Cans'), ('cases', 'Cases'), ('packs', 'Packs (6/12)'), ('liters', 'Liters'), ('kegs', 'Kegs'), ('pallets', 'Pallets')], default='bottles', max_length=20),
        ),
    ]
