# Generated by Django 5.1.15 on 2025-12-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beverage_management', '0004_alter_inventoryitem_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='selection_justification',
            field=models.TextField(blank=True, help_text='Notes on physical canvass'),
        ),
    ]
