# Generated by Django 5.1.15 on 2025-12-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beverage_management', '0005_alter_purchaseorder_selection_justification'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitionform',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='requisitionform',
            name='purpose',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
