# Generated by Django 5.1.15 on 2025-12-08 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beverage_management', '0006_requisitionform_notes_requisitionform_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='requisition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beverage_management.requisitionform'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='selection_justification',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('ordered', 'Ordered'), ('in_transit', 'In Transit'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='ordered', max_length=20),
        ),
    ]
